### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by SenVy-WH** [NVlabs/neuralangelo#50]
When I do
```
EXPERIMENT=toy_example
GROUP=example_group
NAME=example_name
CONFIG=projects/neuralangelo/configs/custom/${EXPERIMENT}.yaml
GPUS=1  # use >1 for multi-GPU training!
torchrun --nproc_per_node=${GPUS} train.py \
    --logdir=logs/${GROUP}/${NAME} \
    --config=${CONFIG} \
    --show_pbar
```
I got this ERROR 
```
terminate called after throwing an instance of 'c10::Error'                                                                                                                                                         
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
triggered by
```
Exception raised from c10_cuda_check_implementation at /opt/pytorch/pytorch/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7fa378c62efc in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7fa378c26486 in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3cc (0x7fa378cf270c in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0xe07fe9 (0x7fa379b1dfe9 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x50a9ca (0x7fa3bc7249ca in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x3db61 (0x7fa378c46b61 in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x1ce (0x7fa378c3e27e in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0xd (0x7fa378c3e3ad in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #8: <unknown function> + 0x7a5188 (0x7fa3bc9bf188 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #9: THPVariable_subclass_dealloc(_object*) + 0x335 (0x7fa3bc9bf545 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #10: /usr/bin/python() [0x5cf323]
frame #11: /usr/bin/python() [0x5d221c]
frame #12: /usr/bin/python() [0x5af53a]
frame #13: /usr/bin/python() [0x613bd5]
frame #14: _PyEval_EvalFrameDefault + 0x8d9b (0x57406b in /usr/bin/python)
frame #15: _PyEval_EvalCodeWithName + 0x26a (0x569cea in /usr/bin/python)
frame #16: _PyFunction_Vectorcall + 0x393 (0x5f6a13 in /usr/bin/python)
frame #17: PyObject_Call + 0x62 (0x5f5c02 in /usr/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x1f2c (0x56d1fc in /usr/bin/python)
frame #19: _PyEval_EvalCodeWithName + 0x26a (0x569cea in /usr/bin/python)
frame #20: /usr/bin/python() [0x50b2b0]
frame #21: _PyEval_EvalFrameDefault + 0x1901 (0x56cbd1 in /usr/bin/python)
frame #22: _PyEval_EvalCodeWithName + 0x26a (0x569cea in /usr/bin/python)
frame #23: /usr/bin/python() [0x50b2b0]
frame #24: _PyEval_EvalFrameDefault + 0x57f2 (0x570ac2 in /usr/bin/python)
frame #25: _PyEval_EvalCodeWithName + 0x26a (0x569cea in /usr/bin/python)
frame #26: /usr/bin/python() [0x50b2b0]
frame #27: _PyEval_EvalFrameDefault + 0x1901 (0x56cbd1 in /usr/bin/python)
frame #28: _PyFunction_Vectorcall + 0x1b6 (0x5f6836 in /usr/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x72d (0x56b9fd in /usr/bin/python)
frame #30: _PyEval_EvalCodeWithName + 0x26a (0x569cea in /usr/bin/python)
frame #31: PyEval_EvalCode + 0x27 (0x68e7b7 in /usr/bin/python)
frame #32: /usr/bin/python() [0x680001]
frame #33: /usr/bin/python() [0x68007f]
frame #34: /usr/bin/python() [0x680121]
frame #35: PyRun_SimpleFileExFlags + 0x197 (0x680db7 in /usr/bin/python)
frame #36: Py_RunMain + 0x212 (0x6b8122 in /usr/bin/python)
frame #37: Py_BytesMain + 0x2d (0x6b84ad in /usr/bin/python)
frame #38: __libc_start_main + 0xf3 (0x7fa405578083 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #39: _start + 0x2e (0x5fb39e in /usr/bin/python)
```
I don't know how to solve it.
I think it may caused by my gcc version
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by chenhsuanlin** [comment]
Hi @SenVy-WH, could you run with the environment variable `CUDA_LAUNCH_BLOCKING=1` as suggested in the log, and help pin down which line in the Pytorch code it fails at? Thanks!

**Comment by SenVy-WH** [comment]
> Hi @SenVy-WH, could you run with the environment variable `CUDA_LAUNCH_BLOCKING=1` as suggested in the log, and help pin down which line in the Pytorch code it fails at? Thanks!

Hi @chenhsuanlin , Thanks for replying.
I've tried `CUDA_LAUNCH_BLOCKING=1` and seems nothing change.
but I got this when I step in the code.
```
Evaluating:  50%|█████████████████████████████████████████████████████▌                                                     | 1/2 [04:38<04:38, 278.14s/it]
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```

**Comment by SenVy-WH** [comment]
> Hi @SenVy-WH, could you run with the environment variable `CUDA_LAUNCH_BLOCKING=1` as suggested in the log, and help pin down which line in the Pytorch code it fails at? Thanks!

Sorry, I accidentally closed this issue by mistake. Reopening it now.
I've tried the `CUDA_LAUNCH_BLOCKING=1` but nothing changed & happend.

But I got this when I tried debug it step by step.
```
Evaluating:  50%|██████████████████████████████████████████████████████                                                      | 1/2 [00:23<00:23, 23.53s/it]
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680542704550/work/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```
It happened in `model.py` on line 220 
```
app = self.appear_embed(sample_idx)[:, None, None]  # [B,1,1,C]
```
Could the data preparation cause this problem or have I configured the image parameters incorrectly?

**Comment by SenVy-WH** [comment]
@chenhsuanlin 
I've checked the shape again.
the `appear_embed` is `Embedding(2,8)`, but the `sample_idx` is `tensor([2,3])`.
So I changed the `num_images` from 2 to 4 in `toy_example.yaml` and then it can run successfully.

But idk why the num is incorrect.
I followed the instructions in Data Preparation step-by-step and generated the `toy_example.yaml` file correctly without running into any issues along the way.

**Comment by chenhsuanlin** [comment]
Thanks for the feedback! Though it's weird, this is likely because `num_images` in our example was set to too small (2). We are working on replacing the toy example with a workable example -- will push the update soon!

**Comment by chenhsuanlin** [comment]
@SenVy-WH we have just updated the toy example video. Could you also try pulling and following the new instructions? If you still run into further issues, please let me know. Thanks!

**Comment by SenVy-WH** [comment]
@chenhsuanlin Thanks for being so responsive! I've tried the new video but still get the same issue as @GondorFu  said.

btw, I found the output always has 
```
Train dataset length: 2                                                                                                                                                                                             
Val dataset length: 4
```
so i change the `subset` from `4` to `2` in the `base.yaml` and it can run successfully.
maybe this num should be syn with `num_images: 2` in `lego.yaml`?

**Comment by chenhsuanlin** [comment]
Yes, indeed if there are <4 training images, `data.val.subset` should be adjusted as well (though these cases should be very rare!). Marking this as a bug to fix.

It seems weird that COLMAP only finds two images on the new toy example though; ideally it should be able to extract 100 frames. I will look into this.

**Comment by SenVy-WH** [comment]
> Yes, indeed if there are <4 training images, `data.val.subset` should be adjusted as well (though these cases should be very rare!). Marking this as a bug to fix.
> 
> It seems weird that COLMAP only finds two images on the new toy example though; ideally it should be able to extract 100 frames. I will look into this.

Hi @chenhsuanlin, I've tried using COLMAP GUI (rather than scripts) to change some settings and keep other settings as default to extract feature and here is what I found:
  1. With `camera_model=RADIAL` & `not selected "Shared for all image"`, COLMAP only finds two images as the scripts.
  2. With `camera_model=RADIAL` & `selected "Shared for all image"`, COLMAP can finds 100 images SOMETIMES.
  3. With `camera_model=SAMPLE_RADIAL` & `selected "Shared for all image"`, COLMAP can finds 100 images ALWAYS.
in case 3, I got 
```
Train dataset length: 100                                                                                                                                                                                            
Val dataset length: 1
```
So I think this two options may be the key to this issue.

**Comment by chenhsuanlin** [comment]
Thanks @SenVy-WH for the feedback! It seems that complex camera model could somewhat hurt registration. We will look into this.

**Comment by chenhsuanlin** [comment]
The `num_images` problem has been fixed (4b2e18e) and the COLMAP script now defaults to the `SIMPLE_RADIAL` camera model (a4e5690). Thanks @SenVy-WH for the feedback -- please feel free to reopen if there are further issues.
